# Config for golangci-lint v2.8.0
version: "2"
linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    # - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    # - forbidigo
    - forcetypeassert
    - funcorder
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    - godoclint
    # - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    # - lll
    - loggercheck
    # - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    # - nlreturn
    - noctx
    # - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    # - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    # - wsl_v5
    - zerologlint
  settings:
    copyloopvar:
      check-alias: true
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
      disable-dec-num-check: false
      disable-dec-order-check: false
      disable-init-func-first-check: false
    depguard:
      rules:
        all:
          list-mode: lax
          deny:
            - pkg: text/template
              desc: use html/template instead of text/template
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (io.ReadCloser).Close
        - (*html/template.Template).Execute
        - (*strings.Builder).WriteString # Returns nil
        - fmt.Fprintf
    errchkjson:
      report-no-exported: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
      default-case-required: true
    goconst:
      numbers: true
    gocritic:
      enable-all: true
      disabled-checks:
        - ifElseChain
        - commentedOutCode
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: false
        underef:
          skipRecvDeref: false
    gosec:
      excludes:
        - G104
      config:
        global:
          audit: true
          show-ignored: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
    grouper:
      const-require-single-const: true
      import-require-single-import: true
      import-require-grouping: true
      type-require-single-type: true
    misspell:
      locale: US
    nestif:
      min-complexity: 10
    nonamedreturns:
      report-error-in-defer: true
    perfsprint:
      err-error: true
    predeclared:
      qualified-name: true
    promlinter:
      strict: true
    reassign:
      patterns:
        - .*
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: nested-structs
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          disabled: true
        - name: get-return
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: enforce-switch-style
          disabled: true
        - name: unhandled-error
          arguments:
            - html/template.Template.Execute
            - net/http.ResponseWriter.Write
            - strings.Builder.WriteString # Returns nil
            - fmt.Fprintf
    tagalign:
      strict: true
    testifylint:
      enable-all: true
    usestdlibvars:
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: main
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
