name: Linting

on:
  push:
    paths:
      - '**/*.go'
  pull_request:
    paths:
      - '**/*.go'

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
        
      - name: Setup and run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest